-- Historical alias of 20260727230138_sprint5_refunds_disputes_debt.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
