-- Historical alias of 20260727221132_sprint4_traceable_transfers_payouts.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
