-- Historical alias of 20260731072657_recover_stale_processing_transfers.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
