-- Historical alias of 20260727235105_sprint6_financial_operations_observability.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
