-- Historical alias of 20260731072954_proportional_dispute_reserve_payout.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
