-- Historical alias of 20260727184658_ensure_unique_stripe_connect_accounts.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
