-- Historical alias of 20260727232711_cancel_recovered_seller_transfers.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
