-- Historical alias of 20260731072511_wallet_lock_ledger_source_of_truth.sql.
-- Intentionally empty: linked environments retain this migration version,
-- while fresh databases must apply the schema change only once.
