import {
  MARKETPLACE_FIXED_FEE,
  MARKETPLACE_PERCENT_FEE,
  STRIPE_STANDARD_EEA_FIXED_FEE,
  STRIPE_STANDARD_EEA_PERCENT_FEE,
} from "../constants";
import { MAX_SHIPPING_COST } from "./shipping";

function roundToCents(value: number): number {
  return Math.round(value * 100) / 100;
}

function ceilToCents(value: number): number {
  return Math.ceil(value * 100 - 1e-9) / 100;
}

function floorToCents(value: number): number {
  return Math.floor(value * 100 + 1e-9) / 100;
}

/**
 * Calculate the buyer protection fee from the seller's requested net price.
 *
 * The fee contains PokeMarket's commission and a conservative simulation of
 * Stripe's standard French EEA-card fee. The Stripe estimate uses the highest
 * supported shipping price because the buyer's destination is not yet known.
 * Grossing up by `(1 - Stripe rate)` also covers Stripe's percentage charged
 * on the protection fee itself.
 */
export function calcBuyerProtectionFee(priceSeller: number): number {
  const marketplaceCommission =
    priceSeller * MARKETPLACE_PERCENT_FEE + MARKETPLACE_FIXED_FEE;
  const simulatedStripeBase = priceSeller + MAX_SHIPPING_COST;
  const feeBeforeGrossUp =
    marketplaceCommission +
    STRIPE_STANDARD_EEA_FIXED_FEE +
    simulatedStripeBase * STRIPE_STANDARD_EEA_PERCENT_FEE;

  return ceilToCents(feeBeforeGrossUp / (1 - STRIPE_STANDARD_EEA_PERCENT_FEE));
}

/**
 * Calculate the display price (buyer-facing) from the seller's net price.
 * display_price = price_seller + buyer_protection
 *
 * Example with the current fee schedule: seller enters 10.00 -> display = 11.22
 */
export function calcDisplayPrice(priceSeller: number): number {
  return roundToCents(priceSeller + calcBuyerProtectionFee(priceSeller));
}

/**
 * Calculate the seller net price from the display price.
 *
 * Rounding down preserves enough buyer protection for arbitrary negotiated
 * display prices while exactly reversing prices generated by calcDisplayPrice.
 */
export function calcPriceSeller(displayPrice: number): number {
  const fixedProtection =
    MARKETPLACE_FIXED_FEE +
    STRIPE_STANDARD_EEA_FIXED_FEE +
    MAX_SHIPPING_COST * STRIPE_STANDARD_EEA_PERCENT_FEE;
  const priceSeller =
    (displayPrice * (1 - STRIPE_STANDARD_EEA_PERCENT_FEE) - fixedProtection) /
    (1 + MARKETPLACE_PERCENT_FEE);

  return Math.max(0.01, floorToCents(priceSeller));
}

/**
 * Calculate the platform fee from display and seller prices.
 * fee = max(0, round(display_price - price_seller, 2))
 */
export function calcFeeAmount(
  displayPrice: number,
  priceSeller: number,
): number {
  return Math.max(0, roundToCents(displayPrice - priceSeller));
}

/**
 * Calculate total buyer pays = display_price + shipping.
 */
export function calcTotalBuyer(
  displayPrice: number,
  shippingCost: number,
): number {
  return roundToCents(displayPrice + shippingCost);
}

/**
 * Parse a user-entered EUR amount with either a comma or a point separator.
 */
export function parseDecimalPrice(value: unknown): number | undefined {
  if (typeof value === "number") {
    return Number.isFinite(value) ? value : undefined;
  }

  if (typeof value !== "string" || value.trim() === "") {
    return undefined;
  }

  const normalized = value.trim().replace(",", ".");
  if (!/^\d+(?:\.\d{0,2})?$/.test(normalized)) {
    return undefined;
  }

  const parsed = Number(normalized);
  return Number.isFinite(parsed) ? parsed : undefined;
}
